### ISSUE TITLE
[iOS for Engineers] Project 1 - Review my app

### ISSUE THREAD

**Issue by laposheureux** [laposheureux/Tips-codepath#1]
My app is finished, please review when you can, thanks! /cc @codepathreview

**Comment by codepathreview** [comment]
Hi Aaron,

Thanks for submitting your pre-work, but your current submission is incomplete. Your app does not complete all the required stories outlined as part of the prework. 

Please review the [prework submission checklist](https://courses.codepath.com/snippets/intro_to_ios/prework.md#heading-submission-checklist) to complete the missing features. Please re-submit your project on your [application dashboard](https://apply.codepath.com/dashboard/), and it will notify us to review again.

**Comment by laposheureux** [comment]
Sorry for the confusion - I misinterpreted the settings request and made a settings bundle and not a settings view controller. I've updated the project to include a separate settings view controller and access it via the navigation controller, but I've also retained the settings bundle and confirmed they stay in sync with each other.

Hopefully that meets the criteria - thanks!
